tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install python-rtmidi --install-option "--no-alsa"
      pip install isobar 
      pip install "kivy[base]" kivy_examples
      DEBIAN_FRONTEND=noninteractive
      sudo apt-get update  -y && sudo apt-get upgrade -y
      sudo apt install xauth x11-utils x11-apps -y


  - command: |
      source venv/bin/activate

  - command: |
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install python-rtmidi --install-option "--no-alsa"
      pip install isobar 
      pip install "kivy[base]" kivy_examples
      DEBIAN_FRONTEND=noninteractive
      sudo apt-get update  -y && sudo apt-get upgrade -y
      sudo apt install xauth xorg x11-apps -y

vscode:
  extensions:
    - ms-python.python
