tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install isobar 
      pip install "kivy[base]" kivy_examples

      # python manage.py migrate
  - command: |
      source venv/bin/activate
      # python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
