tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install isobar 
      pip install "kivy[base]" kivy_examples


  - command: |
      source venv/bin/activate

  - command: |
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install isobar 
      pip install "kivy[base]" kivy_examples


vscode:
  extensions:
    - ms-python.python
